class GameConfig:

    PLAYER_NAME = "Guts"
    STARTING_PLAYER_HEALTH = 500
    STARTING_PLAYER_MAX_HEALTH = 10
    STARTING_PLAYER_BLOOD = 500
    STARTING_PLAYER_KILLS = 0
    STARTING_PLAYER_DAMAGE = 40

    DAMAGE_UPGRADE_COST = 2
    HEALTH_UPGRADE_COST = 5

    BLOOD_PER_ATTACK = 1
    BLOOD_REQUIRED = 5
